INSERT INTO lapangan (id_lapangan, nama_lapangan, deskripsi_lapangan, status_lapangan, id_cabang) VALUES
(1, 'Alpha Court', 'Lapangan futsal indoor dengan lantai vinyl berkualitas tinggi', 'tersedia', 1),
(2, 'Beta Field', 'Lapangan futsal outdoor dengan rumput sintetis kondisi baik', 'maintenance', 2),
(3, 'Gamma Arena', 'Lapangan futsal indoor dengan penerangan LED optimal', 'tersedia', 3),
(4, 'Delta Ground', 'Lapangan futsal outdoor dalam tahap pengecatan ulang', 'maintenance', 4),
(5, 'Epsilon Court', 'Lapangan futsal indoor dengan lantai berstandar FIFA', 'tersedia', 5),
(6, 'Zeta Pitch', 'Lapangan futsal outdoor dengan permukaan sintetis', 'tersedia', 1),
(7, 'Eta Zone', 'Lapangan futsal indoor berpendingin udara', 'tutup', 2),
(8, 'Theta Field', 'Lapangan futsal outdoor dalam perbaikan pagar pembatas', 'maintenance', 3),
(9, 'Iota Ground', 'Lapangan futsal indoor kondisi siap pakai', 'tersedia', 4),
(10, 'Kappa Arena', 'Lapangan futsal outdoor dengan garis lapangan baru', 'tersedia', 5),
(11, 'Lambda Zone', 'Lapangan futsal indoor dengan ventilasi udara alami', 'tutup', 6),
(12, 'Mu Pitch', 'Lapangan futsal outdoor kondisi lapangan berlubang', 'maintenance', 7),
(13, 'Nu Court', 'Lapangan futsal indoor dengan tribun penonton kecil', 'tersedia', 8),
(14, 'Xi Field', 'Lapangan futsal outdoor dalam proses renovasi atap', 'maintenance', 9),
(15, 'Omicron Arena', 'Lapangan futsal indoor dengan pencahayaan LED minimalis', 'tersedia', 10),
(16, 'Pi Zone', 'Lapangan futsal outdoor dengan pagar pembatas rusak', 'maintenance', 6),
(17, 'Rho Pitch', 'Lapangan futsal indoor dengan kondisi lantai licin', 'tersedia', 7),
(18, 'Sigma Court', 'Lapangan futsal outdoor sedang dalam pengecatan', 'maintenance', 8),
(19, 'Tau Ground', 'Lapangan futsal indoor kondisi prima untuk turnamen', 'tersedia', 9),
(20, 'Upsilon Field', 'Lapangan futsal outdoor dengan garis lapangan usang', 'maintenance', 10),
(21, 'Phi Arena', 'Lapangan futsal indoor dengan tribun penonton kapasitas besar', 'tersedia', 1),
(22, 'Chi Zone', 'Lapangan futsal outdoor dalam tahap renovasi jaring gawang', 'maintenance', 2),
(23, 'Psi Ground', 'Lapangan futsal indoor dengan sistem ventilasi otomatis', 'tersedia', 3),
(24, 'Omega Field', 'Lapangan futsal outdoor beralaskan rumput sintetis tua', 'tersedia', 4),
(25, 'Vega Court', 'Lapangan futsal indoor dengan kondisi cat lapangan baru', 'tersedia', 5),
(26, 'Nova Pitch', 'Lapangan futsal outdoor sedang dalam perbaikan garis lapangan', 'maintenance', 6),
(27, 'Quasar Arena', 'Lapangan futsal indoor dalam kondisi sempurna untuk turnamen besar', 'tersedia', 7),
(28, 'Nebula Zone', 'Lapangan futsal outdoor dengan pagar pengaman rendah', 'maintenance', 8),
(29, 'Pulsar Court', 'Lapangan futsal indoor dengan kondisi pendingin rusak', 'tutup', 9),
(30, 'Aurora Field', 'Lapangan futsal outdoor dalam perbaikan tiang gawang', 'tersedia', 10),
(31, 'Horizon Arena', 'Lapangan futsal indoor dengan lantai karet berkualitas premium', 'tersedia', 2),
(32, 'Zenith Zone', 'Lapangan futsal outdoor dengan garis lapangan baru', 'maintenance', 3),
(33, 'Atlas Court', 'Lapangan futsal indoor dengan sistem pencahayaan maksimal', 'tersedia', 4),
(34, 'Cosmos Pitch', 'Lapangan futsal outdoor dalam perawatan rumput sintetis', 'maintenance', 5),
(35, 'Galaxy Ground', 'Lapangan futsal indoor siap pakai untuk latihan harian', 'tersedia', 6);
